CREATE DATABASE BIBLIOTECA2;
GO

USE BIBLIOTECA2;
GO


CREATE TABLE CLIENTE
(COD_CLIENTE INT NOT NULL,
 NOME VARCHAR(50) NOT NULL,
 TELEFONE VARCHAR(20),
 EMAIL VARCHAR(40)
 CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE))
 
 CREATE TABLE REGRA_MULTA
 (COD_REGRA_MULTA INT NOT NULL,
 LIMITE_EMPRESTIMO_DIAS INT NOT NULL,
 MULTA_DIA MONEY NOT NULL,
 CONSTRAINT PK_REGRA_MULTA PRIMARY KEY (COD_REGRA_MULTA))
 
 CREATE TABLE AUTOR
 (COD_AUTOR INT NOT NULL,
 NOME VARCHAR (50)NOT NULL,
 CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR))
 
 CREATE TABLE EDITORA
 (COD_EDITORA INT NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  CONSTRAINT PK_EDITORA PRIMARY KEY (COD_EDITORA))
  
CREATE TABLE LIVRO
(COD_LIVRO INT NOT NULL,
TITULO VARCHAR(50) NOT NULL,
COD_AUTOR INT NOT NULL,
COD_EDITORA INT NOT NULL,
CONSTRAINT PK_LIVRO PRIMARY KEY (COD_LIVRO),
CONSTRAINT FK_LIVRO_AUTOR FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR (COD_AUTOR),
CONSTRAINT FK_LIVRO_EDITORA FOREIGN KEY (COD_EDITORA) REFERENCES EDITORA (COD_EDITORA))

CREATE TABLE EMPRESTIMO
(COD_EMPRESTIMO INT NOT NULL,
 COD_CLIENTE INT NOT NULL,
 COD_LIVRO INT NOT NULL,
 DATA_RETIRADA DATETIME NOT NULL,
 DATA_DEVOLUCAO_PREVISTA DATETIME,
 DATA_DEVOLUCAO DATETIME
 CONSTRAINT PK_EMPRESTIMO PRIMARY KEY (COD_EMPRESTIMO,COD_CLIENTE,COD_LIVRO),
 CONSTRAINT FK_EMPRESTIMO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
 CONSTRAINT FK_EMPRESTIMO_LIVRO FOREIGN KEY (COD_LIVRO)REFERENCES LIVRO (COD_LIVRO))
 
 
CREATE TABLE MULTA
(COD_MULTA INT NOT NULL,
 COD_EMPRESTIMO INT NOT NULL,
 COD_CLIENTE INT NOT NULL,
 COD_LIVRO INT NOT NULL,
 VALOR MONEY NOT NULL,
 CONSTRAINT PK_MULTA PRIMARY KEY (COD_MULTA),
 CONSTRAINT FK_MULTA_EMPRESTIMO FOREIGN KEY (COD_EMPRESTIMO,COD_CLIENTE,COD_LIVRO) REFERENCES EMPRESTIMO (COD_EMPRESTIMO,COD_CLIENTE,COD_LIVRO))

 INSERT INTO CLIENTE VALUES (1,'Edilson Rocha','7070-7070','edilsonrocha@hotmail.com')
 INSERT INTO CLIENTE VALUES (2,'Adailton Nascimento','7070-7070','dada@dada.com')
 INSERT INTO CLIENTE VALUES (3,'Tia Maria','7070-7070','tiamaria@tia.com')

 INSERT INTO EDITORA VALUES (1,'Super Editora')

 INSERT INTO AUTOR VALUES (1,'EINSTEIN')
 INSERT INTO AUTOR VALUES (2,'BILL GATES')

 INSERT INTO LIVRO VALUES (1,'A Teoria da Relatividade',1,1)
 INSERT INTO LIVRO VALUES (2,'Windows 1.0',2,1)

 INSERT INTO EMPRESTIMO VALUES (1,1,1,'01-09-2015','08-09-2015','08-20-2015')
 INSERT INTO EMPRESTIMO VALUES (2,2,1,'01-09-2015','08-09-2015','08-09-2015')

INSERT INTO REGRA_MULTA VALUES (1,7,5.0)


SELECT EMPRESTIMO.COD_EMPRESTIMO,EMPRESTIMO.COD_CLIENTE,CLIENTE.NOME,EMPRESTIMO.COD_LIVRO,LIVRO.TITULO,EMPRESTIMO.DATA_RETIRADA FROM EMPRESTIMO
INNER JOIN CLIENTE ON CLIENTE.COD_CLIENTE=EMPRESTIMO.COD_CLIENTE
INNER JOIN LIVRO ON LIVRO.COD_LIVRO=EMPRESTIMO.COD_LIVRO
